### ISSUE TITLE
Improve Video Media Type

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#108]
The media type is working well for image types but it would be great if we could get some upgrades when used with a video.

1) The video preview is broken.

![screenshot 2020-11-19 at 4 27 33](https://user-images.githubusercontent.com/7152/99578076-95c4fd80-2a1f-11eb-8371-ef7fc574c51c.jpg)

2) It would be nice if we could upload a poster image with the video.    OR even better would be if we could generate the poster automatically from the video.

**Comment by Zoramite** [comment]
I [fixed](https://github.com/grow/grow-ext-editor/commit/a5bdee56cabc5960795e3d7ea33aee70bde381dc#diff-a61a32a77c3f631d6dc69ecd59618b0d6db1b7b28a6edfa9f7d3f6548766820a) the video preview in the latest for videos. I had a bug where I was looking up the video extension instead of the mimetype to match the video formats. :)

For the poster image, that seems to be something that would be included in the `extra` for the media field. I noticed there was a comment in the image schema about not being able to use the `google_image` in the extra... I tried and it was showing up fine for me. Was there another problem with the `google_image` field that I missed?
